import Head from "next/head";
import MainLayout from "@/layout/MainLayout";

import axios from "axios";
import { useQuery } from "react-query";
import { useEffect } from "react";
import { FiTrash } from "react-icons/fi";
import { CgEye } from "react-icons/fi";
import {
  Button,
  Grid,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  Text,
  GridItem,
  Stack,
  Heading,
  Divider,
  ButtonGroup,
  HStack,
  Flex,
  Input,
} from "@chakra-ui/react";
import Image from "next/image";

export default function Home() {
  const { isLoading, error, data } = useQuery("repoData", async () => {
    try {
      const response = await axios.get("http://localhost:5000/api/notes/");
      return response.data;
    } catch (error) {
      console.error(error);
    }
  });
  console.log("allnotes data", data);
  useEffect(() => {}, [data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">
        <h1 className="text-3xl font-bold mb-5">Welcome to My Notes</h1>
        <p>Keep track all yout notes at one place</p>
        <div className="my-5">
          <Input
            type="text"
            bg={"gray.100"}
            px={6}
            py={6}
            fontWeight={"bold"}
            maxW={"50%"}
            rounded={"full"}
            outline="none"
            placeholder="Search note"
          />
        </div>

        <div>
          <Grid container spacing={2}>
            {isLoading ? (
              "Loading"
            ) : (
              <>
                <Grid
                  templateColumns="repeat(4, 1fr)"
                  gap={10}
                  contentCenter="center"
                >
                  {data.map((item, idx) => {
                    return (
                      <GridItem colSpan={1} key={idx}>
                        <Card maxW="sm" bg={"gray.50"} shadow="none">
                          <CardBody>
                            <HStack mt="6" spacing="3">
                              <Flex flexDirection="column" minHeight={150}>
                                <Heading size="md">{item.title}</Heading>
                                <Text mt={5}>{item.content}</Text>
                              </Flex>
                            </HStack>
                          </CardBody>
                          <Divider />
                          <CardFooter p={2}>
                            <ButtonGroup
                              spacing="1"
                              disaplay="flex"
                              justifyContent="center"
                            >
                              <Button variant="solid" colorScheme="red">
                                <FiTrash />
                              </Button>
                              <Button variant="solid" colorScheme="red">
                                <FiTrash />
                              </Button>
                              <Button variant="solid" colorScheme="red">
                                <FiTrash />
                              </Button>
                            </ButtonGroup>
                          </CardFooter>
                        </Card>
                      </GridItem>
                    );
                  })}
                </Grid>
              </>
            )}
          </Grid>
        </div>
      </div>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};
